sudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - jekyll
script:
- bundle exec jekyll build
after_success:
- mkdir tmp
- cd tmp
- git init
- git config user.name ${GIT_NAME}
- git config user.email ${GIT_EMAIL}
- cp -R ../_site/* .
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${TARGET_BRANCH}
  > /dev/null 2>&1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/mrdekk/mrdekk.github.io.git
  - TARGET_BRANCH: master
  - secure: qS7/+7ThZxVMu1S8xfO9j+JJ3WPurZUME1HBPnF7iZDHkC36Ct1jJOX7w95X8R9Z4M0IHYX6uRXQkFKKQcstdGFFPiFLvtRNwEbBwW1k4xPjup/kCIYmtUzT7QF9jng63VW3zyrt41j2gl+JD2h0WOLjHCub/LnoCgnRhAycmHnzibnuELDAHZ46aoDg6aUYIDydaa4jdC42J3zgJEGfiOaUhmK4ZOXKqWw72oS3PR5sP3WRcQ5HILPG/rTM9NzGkVGzUtKdzoCMq92MICzzWn0VAp7Ih2iyhWf4sN5bXS9ZjAAf3GnCysKYIEMo9+ceJqmWOXq0uOqhGym9SoVV3QIJMMg3fgwEb7dL423ZEombHJ3nz4zozBR/HydT+1LHGwhSCigHgnTT9+h0zeW1FkYrqIDD2zCXDbBvXeoQ97JK64HJfNs0yCxviSlSXLm+iGNXa5ufXSmuE+9zh2GMwJ4vk+5vNor7Zj9YoKr2O31qQeIEI+J4xoikFLTTQkWsuG5VFWhCzROE1B/IXE82f8ueDRE42nB5HtxyDCtaw6oGpy3qQuw5kMgrXrM6arEKoGNe6Ngf4zpi2KHGgN53s6iLzv/eDqvV5OuwGVnd/2+DjVrpumvCfl9TUOhNHKtPBSU8voRJ3ot6ogYlqa5xVizrV63MPqErzt/Gcnp2KLA=
  - secure: QQdS+DWs0AL0kO73XnVUxvyy/F17WgkQMJQYx6KoCcx5M5Z/2rgca/kME3jh+F+l8JLh1bVgDvJX+qE/CE6KNuItMuvpP9v736Wed601GfNq9DCDeIVJsQ51PVaj6skfCeI4NTNWwM7s6zjcBDv8cVCviBtd2I93o3ImLQ6cnlmjesW8MocPATHj1zJQ5tEjA8eU+UKYs/KxXGpK+K6dTk/plDkczGXRcS72R6DafrJq1jxtgv3P3YWcVwNjO8iTMWsfH6qvjr/jDARVXwcum2aWNU9JulRJfat/IDCu/z4O82aWShZD+1L83WWvf6/8Hiq2iXpwUO1YJFWpvAk+sUB51mQH6Dv2Nr4FthPYCpLhqoT9YS0mqgSB9hr3g9aFo/h+z9K7Cazhv7TcjwHvbXMNonKhd7+Notz3RS5eOYLNGdJ2vgzJlZHgFnsR+kg6rT5/0izgYU0u1X29M0tJ0rlDnLYbxAIYzg8L3PybSprI/VXxPui18RNUG8EUcgItb779sjWhJXyBrPWv/pK6HJ2ESXAqDdybdANLUIXVchKkN7eXm/aioAzXPXVS45nSSvArmCRG5nAfY+6UqNYyEZ0sPg+bdZnNJ7kIPjmSd9Lb3rJqSDPZdCKTn8teBiBDxHDcztoXLI7Sj0K8Scvqcb+cRh3GlOqfY0C8wDQ73CA=
  - secure: EhGlAOuJuSFJ/4vUiaaTDLXUnAZwEXTQiDCgwMmneDxYxOCmeB6FsuzCZJJ3mts8hElD4Bu5ngxfzh2OXY11f+adis+pbReBiCraVmORPY877I73Pzk8QATtB/I0lfc0u7rEeAcbZMXRbrmfDQ50kiCi2y7c+9V5DgP3ecnCSDiKHJDC4BWDkMF3wsTOwtej1OAc1DR22EduUACrfnGT8abubCJTRBzXPUDP+VX2/18B115zcNqM3WsHw+ZNTdi6YcWIedjtFGZTf+yOUCiTLUK1ClOaS2AQgl6BJofSlDDpMEOa83jWFYaZOYaXZb47ldIXM2BEq324jmPgZUloKrxb5sPBuArGaR60xTbA9znWclT0tKVINvN3ybZ6csdqwg12VxcqQqWfVOwjjkdfVOjrragkQCC8QIAM5fZkOYJHUC8u3YrcVkhHNoyzWoXVcKKEH+8ImwrFqs1zowhO4D0pH0cTHW2+BXHWApkh6NRO2de5WhmXkLjeTh9MoHTlde0/d/CtUs7lVC/2pjYhE2USA8CQOj2Y672XCWlQZ6gvhkpPIvKBViys5/FZ66Q1Y+f4w1DJLTpMvXAj5cF6QjwIZmVh9NYhM0m6D6yxKSlvMRzmFhUtW+C+rr0BgFniPyecYneuaQvtJuwuoyIvv7Oka5C6UaPS2IM65GnMJ88=
