name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - jekyll

env:
  GH_REF: github.com/mrdekk/mrdekk.github.io.git
  TARGET_BRANCH: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler -v 2.7.2
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          mkdir tmp
          cd tmp
          git init
          git config user.name "${GIT_NAME}"
          git config user.email "${GIT_EMAIL}"
          cp -R ../_site/* .
          git add -A .
          git commit -m "Generated Jekyll Site by GitHub Actions - ${GITHUB_RUN_NUMBER}"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${TARGET_BRANCH} > /dev/null 2>&1
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}