name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - jekyll

env:
  GH_REF: github.com/mrdekk/mrdekk.github.io.git
  TARGET_BRANCH: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler -v 2.7.2
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          mkdir tmp
          cd tmp
          git init
          git config user.name "MrDekk"
          git config user.email "mrdekk@yandex.ru"
          cp -R ../_site/* .
          git add -A .
          git commit -m "Generated Jekyll Site by GitHub Actions"
          git push --force --quiet "https://github.com/mrdekk/mrdekk.github.io.git" master:master
